### ISSUE TITLE
Socket error 10053: Software caused connection abort.

### ISSUE THREAD

**Issue by fean** [jeremychild/NCast#5]
Hi,

First of all thanks for all of your work on this neat library!
I'm trying to load media on our styled media receiver application. We have the application already running under our OS X dist so I know the problem isn't with the Chromecast or the media receiver.

This is the code I use to connect to a Chromecast it's within a method with this signature:

`void connect(string name, string url)`

``` C#
DeviceAggregate device;
lock (devicesLock)
    device = devices.Where(da => da.Device.Name == name && da.Device.BaseUrl == url).FirstOrDefault();

if (device != null)
{
    this.device = device;

    device.ConnectionChannel.MessageReceived += ConnectionChromecastDataReceived;
    device.HeartbeatChannel.MessageReceived += HeartbeatChromecastDataReceived;
    device.ReceiverChannel.MessageReceived += ReceiverChromecastDataReceived;
    device.MediaChannel.MessageReceived += MediaChromecastDataReceived;

    await device.Client.Write(MessageFactory.Launch("FFFAA501"));
}
else
    App.Logic.browser.ExecuteScriptAsync("chromecastConnected(false, { message: 'The device details were invalid.'});");
```

After the user has chosen the media he wants to play back, I used this code to try and load the track, this is a preview track from the Spotify preview server to check if it works.

``` C#
var url = "https://p.scdn.co/mp3-preview/18d0a45538122fbe33f22604d0e5608789c10ae4";

var customData = new Dictionary<string, string>();
customData.Add("title:", "Test preview");
customData.Add("thumb", "https://i.scdn.co/image/c171113a197828a6ee8017d1ede2e78c9a7df654");

var req = new LoadRequest(lastStatus.SessionId, new Media(url, null), true, 0.0, customData);
var req_json = req.ToJson();

await device.Client.Write(MessageFactory.Load(lastStatus.TransportId, req_json));
```
When I execute the `Client.Write()` it throws a SocketException saying: `An established connection was aborted by the software in your host machine.`

The Microsoft docs on this error can be read [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx#WSAECONNABORTED). They are saying that it's possibly a time-out of the connection. On discovery I call `StartDevice()` to get the device details. That should also have started the heartbeat, right?

I'm not sure what I'm doing wrong, I probably just forgot something or misinterpreted some of your examples.

**Comment by jeremymudbath** [comment]
I will get to this in the next 24 hours

**Comment by fean** [comment]
Thanks, if you need anything just say the word.

**Comment by fean** [comment]
I just tried a slightly different approach. Because I thought maybe the Chromecast closed the connection after I waited to long before I created a session.

I implemented my own MDns discovery based on the same library:

``` C#
/// <summary>
        /// Starts the Chromecast device discovery.
        /// </summary>
        public void startDiscovery()
        {
            
            browser.ServiceAdded += new EventHandler<ServiceAnnouncementEventArgs>((target, args) =>
            {
                var ChromecastDevice = Helpers.ParseAnnouncement(args.Announcement);
                App.Logic.browser.ExecuteScriptAsync("chromecastDiscovered({name: '" +
                                                        ChromecastDevice.Name + "', url: '" +
                                                        ChromecastDevice.BaseUri.ToString() + "'});");
                lock(devicesLock)
                    devices.Add(ChromecastDevice);

            });
            browser.ServiceRemoved += new EventHandler<ServiceAnnouncementEventArgs>((target, args) =>
            {
                var ChromecastDevice = Helpers.ParseAnnouncement(args.Announcement);
                App.Logic.browser.ExecuteScriptAsync("chromecastLost({name: '" +
                                                        ChromecastDevice.Name + "', url: '" +
                                                        ChromecastDevice.BaseUri.ToString() + "'});");
                lock(devicesLock)
                    devices.Remove(ChromecastDevice);
            });
            browser.StartBrowse("_googlecast._tcp");
        }
```

The parse Anouncement function:

``` C#
/// <summary>
        /// Parses the service announcement.
        /// </summary>
        /// <param name="Announcement">The service announcement details.</param>
        /// <returns>The parsed Chromecast report item.</returns>
        public static ChromecastV2DeviceDiscoveryReportItem ParseAnnouncement(ServiceAnnouncement Announcement)
        {
            var device = Helpers.ParseTxtRecord(Announcement.Txt);

            return new ChromecastV2DeviceDiscoveryReportItem("Google", Convert.ToInt32(device["ve"]), device["md"])
            {
                BaseUri = new System.Uri("http://" + Announcement.Addresses[0] + ":" + Announcement.Port),
                DeviceType = NCast.DeviceType.Chromecast,
                EndPoint = new System.Net.IPEndPoint(Announcement.Addresses[0].Address, Announcement.Port),
                Id = device["id"],
                Interface = Announcement.Addresses[0],
                Name = device["fn"]
            };
        }
```

Then I tried connecting to the Chromecast the moment the user has chosen the Chromecast he/she wants to connect to:

``` C#
        /// <summary>
        /// Connect to the Chromecast and start the MusicX chromecast application.
        /// </summary>
        /// <param name="name">The Chromecast name</param>
        /// <param name="url">The Chromecast connection url</param>
        public void connect(string name, string url)
        {
            Task.Run(async () =>
            {
                ChromecastDeviceDiscoveryReportItem report;
                lock (devicesLock)
                    report = devices.FirstOrDefault(d => d.Name == name && d.BaseUri == new Uri(url));

                if (report != null)
                {
                    var device = new DeviceAggregate(report);

                    await device.StartDevice();

                    device.ConnectionChannel.MessageReceived += ConnectionChromecastDataReceived;
                    device.HeartbeatChannel.MessageReceived += HeartbeatChromecastDataReceived;
                    device.ReceiverChannel.MessageReceived += ReceiverChromecastDataReceived;
                    device.MediaChannel.MessageReceived += MediaChromecastDataReceived;

                    Console.WriteLine("Connection to {0} has been started.", report.Name);
                }
                else
                    App.Logic.browser.ExecuteScriptAsync("chromecastConnected(false, { message: 'The device details were invalid.'});");
            });
        }
```

It threw the same exception a second after I called `await device.StartDevice();`. The actual exception that get's thrown is an `IOException` saying: `Unable to read
data from the transport connection: An established connection was aborted by the
software in your host machine.`.

**Comment by fean** [comment]
Ok, now it works like before, I've altered the code above. I can connect with the Chromecast and launch our receiver application. But the moment I try and load a track, like in my initial issue, it closes the connection again. 

I hooked-up the `ConnectionChannel` to the debug output. Just after I send the request to load media the Chromecast sends the following message: `{"type" : "CLOSE"}`

**Comment by jeremymudbath** [comment]
fean. I am unable to help you with this until tomorrow. I'm so sorry :(

**Comment by fean** [comment]
Oh, that's no problem. I've plenty other stuff to do, so don't worry!

**Comment by BO45** [comment]
If I may add to this conversation. There are actually 2 problems I can currently identify.
 * The Chromecast has a fixed timeout of 5 seconds, that when surpassed through halting at a breakpoint or perhaps over-utilizing the comm thread, will terminate the TLS connection.

* There was a change somewhere between v3 and v4 that when a connection ("CONNECT") is not established to the running app, instead of the client/default receiver all play requests will be rejected. 
It used to work with client-0, but I think now it is mandatory to send a client uid when not talking to the backdrop default app.

So what in my opinion has to be done is:

* reconnect the TLS to the chromecast when the connection is lost (which should be opaque to the client)
* send a "CONNECT" to the correct receiver with a corresponding client id.

**Comment by BO45** [comment]
I forgot a third point.

Chromecast also started sending (again somewhere between v3 and v4) PING requests to the client. So these should probably be answered with a PONG response.

**Comment by fean** [comment]
Thank you for your help so far! I'll try and implement that. I have two questions though. 

1. When `DeviceAggregate.StartDevice()` is called it should start the heart beat. At least, in the function body of `StartDevice()` there is a call to `ChromecastClient.StartHeartbeat()` which sends a "PING" to the Chromecast every 5 seconds. Those get answered by the Chromecast with a "PONG". Would this suffice? Because I've never seen a "PING" from the Chromecast on the `HeartbeatChannel`.

2. What ID should I be using in the "CONNECT" message? The App id? Or if there is no session should I do "LAUNCH" first and then use the session id in the "CONNECT" message to join the session?

**Comment by BO45** [comment]
1. They come in very sporadically. I have yet to see a pattern behind it. For example when I launch the default media receiver I got a "PING" from the chromecast after 25 seconds of idle. Then another 25 seconds later I received a "CLOSE". Then Chromecast switched back to backdrop. So the ping could be some type of app keep-alive mechanism, for the chromecast to know whether it should stay or switch back to backdrop.

2. When in backdrop it is sender/receiver-0. But after you LAUNCH an app, you will receive a RECEIVER_STATUS, which contains a "transportId", that is the "DestinationId". The "SourceId" should be random e.g. "client-" + (1000 + rand() % 9999). From that you form your CONNECT and all future messages to the app, should use that unique client id.

**Comment by fean** [comment]
Thank you, that is very helpful!

This is the full stack-trace. It takes some time to appear which I think suggests that after the first "PONG" comes back from the Chromecast this Exception occurs.

```
System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine. ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartFrameHeader(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.StartReading(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int3A first chance exception of type 'System.IO.IOException' occurred in System.dll
2 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at NCast.Protocols.CASTV2.ChromecastClient.ReadPacket() in c:\Users\Admin\Documents\Spotty\Spotty.Player.win32\NCast\Protocols\CASTV2\ChromecastClient.cs:line 117
```
